### ISSUE TITLE
Remove binaries and ignore them

### ISSUE THREAD

**Issue by wernight** [pazz/urwidtrees#12]
Should probably remove:

* `docs/examples/example1.pyc`
* `docs/examples/__pycache__/`

Add a `.gitignore` with https://github.com/github/gitignore/blob/master/Python.gitignore or at least `*.pyc`.

**Comment by wernight** [comment]
I wonder also if `docs/source/.ropeproject` should be under source control.

**Comment by pazz** [comment]
youre right, i think all of this can go


Quoting Werner Beroux (2015-03-12 16:54:13)

**Comment by bwesterb** [comment]
It's fixed in PR #19
