### ISSUE TITLE
Fix dependency specification in setup.py

### ISSUE THREAD

**Issue by shaded-enmity** [pazz/urwidtrees#28]
The correct key name that is picked up by `pip` in `setup.py` is `install_requires`:
https://github.com/pazz/urwidtrees/blob/master/setup.py#L15

Trying to install `urwidtrees` without having `urwid` installed results in:
```
> $ pip install urwidtrees                                                                                    [±master ●]
Collecting urwidtrees
  Using cached urwidtrees-1.0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-VGDG1V/urwidtrees/setup.py", line 4, in <module>
        import urwidtrees.version as v
      File "urwidtrees/__init__.py", line 6, in <module>
        from .decoration import DecoratedTree, CollapsibleTree
      File "urwidtrees/decoration.py", line 4, in <module>
        import urwid
    ImportError: No module named urwid
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-VGDG1V/urwidtrees/
```

**Comment by pazz** [comment]
I think this could be fixed with an

    install_requires=['urwid']

in the setup.py. I am not maintaining the pip version myself, but would accept a
PR for this.

**Comment by lucc** [comment]
I am not sure if this will solve it:
```
git clone https://github.com/pazz/urwidtrees
cd urwidtrees
virtualenv foo
source foo/bin/activate
sed -i 's/)$/install_requires=["urwid"])/' setup.py
pip install .
```
still gives the import error.

The question is rather: I think it would be better to either put the version definition somewhere else or remove all these imports from __init__. Then we can import the version during install without importing the complete package (which I hope is not used during install, just the version number).

**Comment by lucc** [comment]
After some tests I conclude that you should either hard code the version and other meta info into setup.py or not import everything into \__init__.py . Becasue \__init__ will be loaded no matter which submodule of a package you import so the import error will persist.

**Comment by lucc** [comment]
This is also relevant to pazz/alot#886.
