### ISSUE TITLE
Doc/Howto up-down navigate at current depth?

### ISSUE THREAD

**Issue by ava-dylang** [pazz/urwidtrees#40]
In trying the demos the up and down keys walked into every child, I couldn't figure out (as a dumb user) how to jump to the next sibling, which is what i feel like up and down should do instead of walking to the next child. Is that configurable? (i  didn't see it in my rushed view of the examples/docs)

**Comment by pazz** [comment]
Those are hardcoded ut you can over-ride the `TreeBox.keypress` method if you prefer other keypresses..
