### ISSUE TITLE
Tree view with cwd as root

### ISSUE THREAD

**Issue by yochem** [pazz/urwidtrees#44]
Hey, sorry for the question but I've been going through the examples today and I can't find a way to change the code so the root of the tree will be the current working directory. Is this possible to do?

**Comment by pazz** [comment]
You mean in example 4?
I think youd need to adjust the DirectoryTree class so that its method
`parent_position` returns None for the directory you want as root.

**Comment by yochem** [comment]
thanks! This worked great.
