### ISSUE TITLE
setup.py: mock should not be in both install_requires and extras_require

### ISSUE THREAD

**Issue by lleseur** [pazz/urwidtrees#48]
It looks like mock is only used for the docs, so I would suggest removing it from install_requires.

Also, since it is included as unittest.mock in Python 3.3+, I would suggest using `'mock;python_version<"3.3"'` to only pull it when needed. Commit 76a79ae4288f720f4d3cd4a580d4eabcdd54c38b already provides support for it.

**Comment by pazz** [comment]
Thanks, that's be OK with me. Can you send a PR?
________________________________
