### ISSUE TITLE
help adding/removing child nodes while SimpleTree is running

### ISSUE THREAD

**Issue by presto-dev** [pazz/urwidtrees#50]
How do I add/rename/delete tree nodes while the widget is live?

I understand how to build the initial structure from your examples, I am creating a SimpleTree and adding it to a CollapsibleArrowTree, everything is working fine, i can save and reload the tree from an XML file

but while the Tree is running, what is the correct way to add a new child, or delete a child from the tree?

I have been studying this API for several days I and I feel like I'm missing something very basic here.

My first method was to do it the way I initially built the tree, but manually stepping thru SimpleTree._treelist and making the changes. 

My second method was to make the changes in the XML, rebuild the tree from scratch and reassign the SimpleTree to the CollapsibleArrow tree during runtime.

both attempts I was able to create a child node where I wanted to, and I could delete a node if it had a sibling beneath it, otherwise i get "TypeError: 'NoneType' object is not subscriptable" on urwidtrees/tree.py line 192

i'm sorry to bother you with this novice question but i would appreciate any advice

thank you

**Comment by pazz** [comment]
Quoting presto-dev (2021-01-05 20:05:52)

> How do I add/rename/delete tree nodes while the widget is live?
>
> I understand how to build the initial structure from your examples, I am
> creating a SimpleTree and adding it to a CollapsibleArrowTree, everything is
> working fine, i can save and reload the tree from an XML file
> 
> but while the Tree is running, what is the correct way to add a new child, or
> delete a child from the tree?

Have a look at the "Dynamic List" example. You need to make changes to the underlying "Tree" structure.
The easiest way I believe is to use a SimpleTree, which maintains widgets in some dictionary or so,
and directly modify this dict, like in this dynamic example, line 23.

It is possible that you need to refresh the TreeBox widget for changes to be visible.

 
> I have been studying this API for several days I and I feel like I'm missing
> something very basic here.
> 
> My first method was to do it the way I initially built the tree, but manually
> stepping thru SimpleTree._treelist and making the changes.

That should work as well. Don't forget to refresh the TreeBox.
 
> My second method was to make the changes in the XML, rebuild the tree from
> scratch and reassign the SimpleTree to the CollapsibleArrow tree during
> runtime.
> 
> both attempts I was able to create a child node where I wanted to, and I could
> delete a node if it had a sibling beneath it, otherwise i get "TypeError:
> 'NoneType' object is not subscriptable" on urwidtrees/tree.py line 192

SimpleTree stores the structure as lists of (lists of ..) *tuples*!
If you want nothing, then you'd put an empty list I guess.

Have fun,
P

**Comment by presto-dev** [comment]
Thank you for your reply. I have uploaded a working example of how I am adding/renaming/deleting nodes.

[add_rem_test.txt](https://github.com/pazz/urwidtrees/files/5778415/add_rem_test.txt)

I am performing these actions by directly accessing the _treelist in the SimpleTree, and refreshing my TreeBox.

add/rename/delete nodes are successul except for one situation where a node is deleted that does not have any peers after it.

When I remove a node that has no peers after it, I get a traceback indicating something internal to the SimpleTree has been set to None

If you can please look it over and offer advice I would appreciate the help.

thank you :)

**Comment by presto-dev** [comment]
I forgot to remove my debugging stuff from the script, here's a copy with all of the debugging imports removed.

[add_rem_test.txt](https://github.com/pazz/urwidtrees/files/5778517/add_rem_test.txt)

**Comment by pazz** [comment]
sorry but I can't spend time on debugging your code. Perhaps someone on stackexchange.com is willing to look into it...

**Comment by presto-dev** [comment]
I apologize I should have stuck with your examples.

referencing "example3.collapse.py"

removing "Grand Grandchild 1" while it is selected causes an exception
removing "Grand Grandchild 0" while it is selected does not cause an exception
