### ISSUE TITLE
update version

### ISSUE THREAD

**Issue by cinghiopinghio** [pazz/urwidtrees#7]
Hi @pazz,

I'm running the testing branch of alot which require urwidtrees version 1.0.
This is tagged to be 1.0 but in `__init__.py` version is still 0.1, breaking manual installation.
Could you fix that? Should I send a PR for such a small thing?

cheers

**Comment by pazz** [comment]
hi! thanks for mentioning this! I had it updated only locally but did not push it for some reason :/
anyways, should be fixed now
