### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by wernight** [pazz/urwidtrees#8]
May do, but should make it official:

    pip install git+https://github.com/pazz/urwidtrees.git

**Comment by pazz** [comment]
well, this is the same for every python lib no?

```
python setup.py install [--user]
```

**Comment by wernight** [comment]
That's the legacy way. Most people use PIP nowadays, and very rarely directly with a repository, but rather with one of the released versions, like:

    pip install urwid
    pip install urwidtrees==1.0.0

Supposing you want explicitely version 1.0.0, which allows version pinning in `requirements.txt` or the equivalent in *Buildout*.

**Comment by bwesterb** [comment]
@wernight  urwidtrees is in pypi now:  https://pypi.python.org/pypi/urwidtrees/

I guess this issue can be closed.

**Comment by wernight** [comment]
Could close, but I'd suggest to add an "Install" section in README.md.
